### ISSUE TITLE
is scrolling supported? I get an error if i explicitly ask Fuji to scroll. 

### ISSUE THREAD

**Issue by seshubonam** [normal-computing/fuji-web#174]
**Is your feature request related to a problem? Please describe.**
Need to scroll to get more content from webpage if relevant answer is not found. 

**Describe the solution you'd like**
scrolling step could be set when the confidence score of the latest action history is lower than a threshold for the input query. 

**Describe alternatives you've considered**
may be manually scroll and run the query

**Additional context**
scroll would be useful because the ui of webpage sometimes gets crammed due to the fuji extention window using part of the webpage space.

**Comment by seshubonam** [comment]
<img width="1280" alt="Screenshot 2024-05-26 at 3 28 25 AM" src="https://github.com/normal-computing/fuji-web/assets/1757478/aa6be36f-d878-46b2-bc54-58983a8d8165">
 For scrolling a web page, I get this error after trying in different websites

**Comment by mondaychen** [comment]
Thanks for reporting this issue. This problem was introduce when I was trying to fix another issue in #170. I'll submit a fix soon

**Comment by seshubonam** [comment]
also the decision to use chrome extension is good because the other automations ive tested open a chrome browser instance that doesnt support login due to security reasons. 
working with existing chrome tabs gives an edge. ⚡

**Comment by mondaychen** [comment]
This should work fine in v2.1.1.3! Let me know if it persists or if you noticed anything else!
